spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 100860

  #\u6267\u884Csql\u811A\u672C
  sql:
    init:
      mode: never

#\u5F00\u59CB\u65E5\u5FD7
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
