#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 100860


logging:
  level:
    com.user.mybatis.mapper: debug
mybatis:
  configuration:
    #开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    #map-underscore-to-camel-case: true
    #启用缓存
    cache-enabled: false
    #延迟加载
    aggressive-lazy-loading: true
  #mapper.xml 文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  #mybatis主配置文件 位置
  config-location: classpath:/mybatis-config.xml




