server:
  servlet:
    context-path: /blog
  port: 8001

#springmvc
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  config:
    import: classpath:/config/app-base.yml,classpath:/config/db.yml


#mybatis
mybatis:
  configuration:
    #\u65E5\u5FD7
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #\u9A7C\u5CF0\u6620\u5C04
    map-underscore-to-camel-case: true
  #\u6620\u5C04\u6587\u4EF6\u7684\u4F4D\u7F6E
  mapper-locations: classpath:/mappers/**/*.xml
